# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ca7e46eb1c960339cd56f3ea92acd26359dd15bfe5157051311537861785b2ebdc31b8d5ea2bdebab79e238e5b5a0dc73e814702f792c10ee8572bb91eca268

test:
  secret_key_base: 12c7d5499ac7520e7e0e86767a392d855a9e0e2d12d54fc45eee686f0531678f62b0568df2f11bbf51987179b12db581e90ecc24cf87f0fa540bac19ecdcb568

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
